name: OpenClaw
options:
  bundleIdPrefix: com.aahalife
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  OpenClaw:
    type: application
    platform: iOS
    sources:
      - path: OpenClaw
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.aahalife.openclaw
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "OpenClaw"
        SWIFT_EMIT_LOC_STRINGS: YES
    scheme:
      testTargets:
        - OpenClawTests
        - OpenClawUITests

  OpenClawTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OpenClawTests
    dependencies:
      - target: OpenClaw
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aahalife.openclaw.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OpenClaw.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/OpenClaw"
        BUNDLE_LOADER: "$(TEST_HOST)"

  OpenClawUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OpenClawUITests
    dependencies:
      - target: OpenClaw
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aahalife.openclaw.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: OpenClaw
