# Temporal Dynamic Configuration for Development
# See: https://docs.temporal.io/references/dynamic-configuration

frontend.enableClientVersionCheck:
  - value: true
    constraints: {}

history.persistenceMaxQPS:
  - value: 3000
    constraints: {}

frontend.persistenceMaxQPS:
  - value: 3000
    constraints: {}

matching.numTaskqueueReadPartitions:
  - value: 5
    constraints: {}

matching.numTaskqueueWritePartitions:
  - value: 5
    constraints: {}

system.enableActivityEagerExecution:
  - value: true
    constraints: {}

system.enableEagerWorkflowStart:
  - value: true
    constraints: {}

limit.maxIDLength:
  - value: 1000
    constraints: {}

frontend.enableUpdateWorkflowExecution:
  - value: true
    constraints: {}
